config/urls.py
import os
from django.contrib import admin
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

from apps import users

urlpatterns = [
    # admin
    path(os.environ.get("ADMIN_URL"), admin.site.urls),
    # swagger
    path(
        'os.environ.get("SWAGGER_DOWNLOAD_URL")',
        SpectacularAPIView.as_view(),
        name="schema",
    ),
    path(
        os.environ.get("SWAGGER_URL"),
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        os.environ.get("REDOC_URL"),
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    # local apps
    path("users/", include("apps.users.urls", namespace="users")),
    path("users/", include("apps.users.urls", namespace="users")),
    path('admin/', admin.site.urls),
    path('schema/', SpectacularAPIView.as_view(), name='schema'),
    path('swagger/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('', include('apps.onlinemarket.urls')),
    path('users/', include('apps.users.urls')),
    path('', include('admin_tabler.urls')),
    path('', TemplateView.as_view(template_name="base.html"), name="home"),  # Bosh sahifa
    path('products/', include('apps.onlinemarket.urls')), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/onlinemarket/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.conf import settings

class Product(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, max_length=70)
    description = models.TextField()
    price = models.IntegerField()
    is_new = models.BooleanField(default=False)
    is_discounted = models.BooleanField(default=False)
    category = models.ForeignKey('Category', default=False, on_delete=models.CASCADE)
    is_hot = models.BooleanField(default=False, verbose_name="Hot Mahsulotmi?")
    brand = models.ForeignKey('Brand', default=None, on_delete=models.CASCADE)
    image = models.ImageField(
        default='default_product.png', null=True, upload_to='product_img'
    )
    sale_product_price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    
    # yangi maydon:
    in_stock = models.BooleanField(default=True, verbose_name='Есть в наличии')

    def __str__(self):
        return self.name

    def __str__(self):
        return self.title
class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')

    def clean(self):
        if self.product.images.count() >= 10:
            raise ValidationError("You can only upload up to 10 images for a product.")

    def __str__(self):
        return f"Image for {self.product.title}"

class Brand(models.Model):
    name = models.CharField(max_length=50)
    icon = models.ImageField(upload_to='brands_icon')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Slide(models.Model):
    image = models.ImageField(upload_to='slide_images')


class CartItem(models.Model):
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()

    def __str__(self):
        return self.product.title

    def total_price(self):
        return self.product.price * self.quantity



class Region(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class District(models.Model):
    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return f"{self.name} ({self.region.name})"

class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    address = models.TextField()
    
    def __str__(self):
        return f"{self.name} - {self.district.name}"



# Buyurtma modeli
class Order(models.Model):
    address = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    total_price = models.IntegerField()
    customer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True)


    def __str__(self):
        return 'Order # %s' % (str(self.id))


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name="order_products")
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    amount = models.IntegerField()
    total = models.IntegerField()
    

    def __str__(self):
        return '%s x%s - %s' % (self.product, self.amount, self.order.customer.username)


RATE_CHOICES = [
    (1, '🗑️ - Trash'),
    (2, '👎 - Bad'),
    (3, '😐 - Ok'),
    (4, '👍 - Good'),
    (5, '🌟 - Perfect'),
]


class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    text = models.TextField(max_length=300, blank=True)
    rate = models.PositiveBigIntegerField(choices=RATE_CHOICES, null=True)

    def __str__(self):
        return self.user.username



class SearchImage(models.Model):
    keyword = models.CharField(max_length=255, unique=True, verbose_name="Qidiruv Kalit So'zi")
    image = models.ImageField(upload_to='search_images/', verbose_name="Rasm")
    is_pinned = models.BooleanField(default=True, verbose_name="Natijalarga Pinned qilsinmi?")

    def __str__(self):
        return f"{self.keyword} (Pinned: {self.is_pinned})"

templates/base.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Online shop | Internet magazin</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.4/css/bulma.min.css"
        integrity="sha512-HqxHUkJM0SYcbvxUw5P60SzdOTy/QVwA1JJrvaXJv4q7lmbDZCmZaqz01UPOaQveoxfYRv1tHozWGPMcuTBuvQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        
</head>

<body>
    <div class="container">
        <section class="hero">
            <div class="hero-head">
                <nav class="navbar p-6" role="navigation" aria-label="main navigation"
                    style="box-shadow: 10px 10px 50px 0 rgb(200,200,200); position: sticky; top: 10%; border-radius:0 0 100px 100px">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="{% url 'product_list' %}">

                            <img src="{% static 'images/2023-06-05 14.23.26.jpg' %}">
                        </a>
                        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                            data-target="navbarBasicExample">
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                            <span aria-hidden="true"></span>
                        </a>
                    </div>
                    <div id="navbarBasicExample" class="navbar-menu">
                        <div class="navbar-start">
                            <nav class="navbar" role="navigation" aria-label="dropdown navigation">
                                <div class="navbar-item has-dropdown is-hoverable">
                                    <a class="navbar-link">
                                        Categories
                                    </a>

                                    <div class="navbar-dropdown">
                                        {% for brand in brands %}
                                        <a href="{% url 'product_list' %}?brand={{ brand.pk }}" class="navbar-item"
                                            style="font-size: 15px">
                                            {{ brand }}
                                        </a>
                                        {% endfor %}


                                    </div>
                                </div>
                            </nav>
                        </div>
                        <div class="navbar-end">
                            <span class="navbar-item">
                                <form action="{% url 'product_list' %}" method="get">
                                    <div class="field has-addons">
                                        <div class="control">
                                            <input style="width: 500px;" class="input" type="search" placeholder="Find a repository" name="search">
                                        </div>
                                        <div class="control">
                                            <button type="submit" class="button is-info" style="width: 80px;">
                                                <i class="fa-solid fa-magnifying-glass"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </span>
                        </div>
                        <div class="navbar-end">
                            <span class="navbar-item">
                                {% if request.user.is_authenticated %}
                                <!-- <a class="navbar-item button is-light mx-2 mx-2-mobile">
                            Xush kelibsiz: {{ user }}
                        </a> -->
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                <div class="buttons">
                                    <a href="{% url 'orders' %}" class="button is-warning order">
                                        <strong>Xaridorlar ro'yxati</strong>
                                    </a>
                                    <a href="{% url 'cart' %}" class="button is-info order">
                                        <ion-icon name="cart-outline" class="mr-2 is-size-3"></ion-icon>
                                        <strong>Savatcha</strong>
                                    </a>

                                    <a href="{% url 'sign_out' %}" class="button is-danger">
                                        <strong>Chiqish</strong>
                                    </a>
                                </div>
                                {% endif %}
                            </span>
                        </div>
                    </div>


                </nav>
            </div>
            <div class="hero-body">
                {% block auth %}
                {% endblock %}

                {% block slider %}
                {% endblock %}

                {% block content %}
                {% endblock %}
            </div>
        </section>

    </div>



    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
    <script>
        bulmaCarousel.attach('#carousel-demo', {
            slidesToScroll: 1,
            slidesToShow: 1,
            infinite: true,
        });
    </script>
    <script src="{% static 'js/script.js' %}"></script>


</body>

</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="card mb-4 p-4 has-text-weight-bold is-size-4">
    <a class="button has-text-left is-danger" href="{% url 'product_list' %}">Asosiy sahifa</a>
    {% if cart_items %}
    <a class="button has-text-right is-info" href="{% url 'create_order' %}">Mahsulotni rasmiylashtirish</a>
    {% endif %}
    <hr>
    <div class="columns has-text-centered box">
        <div class="column">
            <div class="content">{{ total_quantity }} ta Mahsulot olindi </div>
        </div>
        <div class="column">
            <div class="content">Jami narx: {{ total_price }} $</div>
        </div>
    </div>
</div>

<div class="card p-5">
    <div class="content">
        {% if cart_items %}
        <div class="table has-text-centered">
            <table class="table is-striped is-bordered">
                <thead>
                    <tr>
                        <th>Image</th>
                        <th>Nomi</th>
                        <th>Narxi</th>
                        <th>Soni</th>
                        <th>Jami</th>
                        <th>O'chirish</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                    <tr>
                        <td>
                            <img src="{{ item.product.image.url }}" alt="" width="100" height="100">
                        </td>
                        <td>{{ item.product.title | slice:":20" }}...</td>
                        <td>{{ item.product.price }} $</td>
                        <td>{{ item.quantity }}

                            <div class="quantity ml-3">

                                <a href="{% url 'edit_cart_item' item.id %}?action">
                                    <img src="{% static 'images/arrow-up.png' %}" class="arrows" alt="">
                                </a>
                                <a href="{% url 'edit_cart_item' item.id %}?action=take">
                                    <img src="{% static 'images/arrow-down.png' %}" class="arrows" alt="">
                                </a>

                            </div>
                        </td>
                        <td>{{ item.total_price }} $</td>
                        <td>
                            <a href="{% url 'delete_item' item.pk %}" style="font-size: 20px; color: black;">
                                <ion-icon name="trash-outline"></ion-icon>
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="title has-text-centered">Sizda hali hech narsa yoq.</p>
        <p class="subtitle has-text-centered"> <a href="{% url 'product_list' %}">Biror mahsulot Xarid qilishingiz
                mumkin</a></p>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/dashboard.html
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<canvas id="productChart"></canvas>

<script>
    fetch("/api/product-chart/")  // views.py da yaratgan API'ni chaqiramiz
    .then(response => response.json())
    .then(data => {
        let ctx = document.getElementById('productChart').getContext('2d');
        new Chart(ctx, {
            type: 'bar',
            data: {
                labels: data.categories,
                datasets: [{
                    label: 'Mahsulotlar soni',
                    data: data.totals,
                    backgroundColor: 'rgba(75, 192, 192, 0.6)',
                    borderColor: 'rgba(75, 192, 192, 1)',
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    });
</script>

templates/dropdown_list_options.html
<option value="">---------</option>
{% for item in items %}
<option value="{{ item.pk }}">{{ item.name }}</option>
{% endfor %}

templates/order_change_list.html
{% extends "order-change_list.html" %}
{% block result_list %}
    {{ block.super }}
    <script>
        document.addEventListener("DOMContentLoaded", function() {
            const rows = document.querySelectorAll("tr.model-order");
            rows.forEach(row => {
                const orderId = row.dataset.objectId;
                const detailsLink = document.createElement("a");
                detailsLink.href = `/admin/onlinemarket/order/${orderId}/details/`;
                detailsLink.textContent = "View Details";
                row.querySelector(".field-id").appendChild(detailsLink);
            });
        });
    </script>
{% endblock %}

templates/order_creation_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="columns">
        <!-- Buyurtma formasi -->
        <div class="column is-5">
            <div class="box">
                <h2 class="title is-4">Buyurtma ma'lumotlari</h2>
                <form method="post" id="orderForm" action="{% url 'create_order' %}">
                    {% csrf_token %}
                    
                    <!-- Viloyat tanlash -->
                    <div class="field">
                        <label class="label">Viloyat</label>
                        <div class="control">
                            <div class="select is-fullwidth">
                                {{ form.region }}
                            </div>
                        </div>
                    </div>
                    
                    <!-- Tuman tanlash -->
                    <div class="field">
                        <label class="label">Tuman/Shahar</label>
                        <div class="control">
                            <div class="select is-fullwidth">
                                {{ form.district }}
                            </div>
                        </div>
                    </div>
                    
                    <!-- Filial tanlash -->
                    <div class="field">
                        <label class="label">Filial</label>
                        <div class="control">
                            <div class="select is-fullwidth">
                                {{ form.branch }}
                            </div>
                        </div>
                    </div>
                    
                    <!-- Telefon raqam -->
                    <div class="field">
                        <label class="label">Telefon raqam</label>
                        <div class="control">
                            {{ form.phone }}
                        </div>
                        {% if form.phone.errors %}
                            <p class="help is-danger">{{ form.phone.errors }}</p>
                        {% endif %}
                    </div>
                    
                    <!-- Manzil -->
                    <div class="field">
                        <label class="label">To'liq manzil</label>
                        <div class="control">
                            {{ form.address }}
                        </div>
                        {% if form.address.errors %}
                            <p class="help is-danger">{{ form.address.errors }}</p>
                        {% endif %}
                    </div>
                    
                    <div class="field">
                        <div class="control">
                            <button type="submit" class="button is-primary is-fullwidth">
                                <span class="icon">
                                    <i class="fas fa-paper-plane"></i>
                                </span>
                                <span>Buyurtmani tasdiqlash</span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        
        <!-- Savatdagi mahsulotlar -->
        <div class="column is-7">
            <div class="box">
                <h2 class="title is-4">Savatdagi mahsulotlar</h2>
                <a class="button is-danger is-outlined mb-4" href="{% url 'cart' %}">
                    <span class="icon">
                        <i class="fas fa-arrow-left"></i>
                    </span>
                    <span>Savatga qaytish</span>
                </a>
                
                <div class="table-container">
                    <table class="table is-fullwidth is-striped">
                        <thead>
                            <tr>
                                <th>Rasm</th>
                                <th>Mahsulot</th>
                                <th>Narxi</th>
                                <th>Miqdori</th>
                                <th>Jami</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="image is-64x64">
                                        <img src="{{ item.product.image.url }}" alt="{{ item.product.title }}">
                                    </figure>
                                </td>
                                <td>{{ item.product.title }}</td>
                                <td>{{ item.product.price }} so'm</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.total_price }} so'm</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colspan="4">Umumiy summa</th>
                                <th>{{ cart_total }} so'm</th>
                            </tr>
                        </tfoot>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- AJAX scriptlari -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function(){
    // Viloyat o'zgarganda tumanlarni yuklash
    $("#id_region").change(function(){
        var regionId = $(this).val();
        if(regionId){
            $.ajax({
                url: "{% url 'load_districts' %}",
                data: {'region_id': regionId},
                success: function(data){
                    $("#id_district").html(data);
                    $("#id_branch").html('<option value="">Filialni tanlang</option>');
                }
            });
        } else {
            $("#id_district").html('<option value="">Tumanni tanlang</option>');
            $("#id_branch").html('<option value="">Filialni tanlang</option>');
        }
    });
    
    // Tuman o'zgarganda filiallarni yuklash
    $("#id_district").change(function(){
        var districtId = $(this).val();
        if(districtId){
            $.ajax({
                url: "{% url 'load_branches' %}",
                data: {'district_id': districtId},
                success: function(data){
                    $("#id_branch").html(data);
                }
            });
        } else {
            $("#id_branch").html('<option value="">Filialni tanlang</option>');
        }
    });
});
</script>
{% endblock %}

templates/orders.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="card p-5">
        <div class="content">
            {% if orders %}
            <div class="title has-text-centered">My recent orders</div>
            <table class="table has-text-centered">
                <thead>
                    <tr>
                        <th>Order number</th>
                        <th>Product</th>
                        <th>Total</th>
                        <th>Status</th>
                        <th>Payed</th>
                    </tr>
                </thead>
                <tbody>

                    {% for order in orders %}
                    <tr>
                        <td>{{ order }}</td>
                        <td>
                            {% for order_product in order.order_products.all %}
                            <a href="{% url 'product_detail' order_product.product.pk %}">
                                {{ order_product | truncatewords:5  }}
                            </a>,
                            {% endfor %}
                        </td>
                        <td>{{ order.total_price }} $</td>
                        <td>In consideration</td>
                        <td>Not paid</td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
            {% else %}
            <p class="title has-text-centered">
                Nothing ordered yet
            </p>
            {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="section product-detail">
    <div class="columns">
        <div class="column is-6-desktop is-12-mobile">
            <div class="box">
                <!-- Asosiy rasm -->
                <figure class="image product-detail-image">
                    <img id="mainImage" src="{{ product.image.url }}" alt="{{ product.title }}">
                </figure>

                <!-- Kichik rasmlar -->
                <div class="thumbnails" style="display: flex; gap: 10px; margin-top: 10px;">
                    {% for image in product.images.all %}
                        <img src="{{ image.image.url }}" alt="Thumbnail" class="thumbnail" 
                             onclick="changeMainImage('{{ image.image.url }}')" 
                             style="width: 80px; height: 80px; cursor: pointer; border: 2px solid transparent;">
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="column is-6-desktop is-12-mobile">
            <div class="content">
                <p class="title is-size-3">
                    {{ product.title }}
                    {% if product.is_new %}
                        <span class="tag is-danger">New!</span>
                    {% endif %}
                    {% if product.is_discounted %}
                        <span class="tag is-primary">Discount! -20%</span>
                    {% endif %}
                </p>
                <p class="title is-size-3 has-text-info">{{ product.price }} $</p>
                <p class="title is-size-5 has-text-grey-light">0 отзывов</p>
                <p class="title">Brand: {{ product.brand }}</p>
                <p class="has-text-weight-bold has-text-success">
                    {% if product.in_stock %}
                        <span class="tag is-success is-light">Есть в наличии</span>
                    {% else %}
                        <span class="tag is-danger is-light">Нет в наличии</span>
                    {% endif %}
                </p>

                <p class="title is-size-4">
                    Поделится:
                    <span class="is-size-4 mx-3">
                        <a href="#"><ion-icon name="logo-whatsapp"></ion-icon></a>
                        <a href="#"><ion-icon name="logo-youtube"></ion-icon></a>
                        <a href="#"><ion-icon name="logo-facebook"></ion-icon></a>
                    </span>
                </p>

                <a href="{% url 'rate_product' product.pk %}" class="button is-warning">Leave review</a>
                <a href="{% url 'product_list' %}" class="button is-danger">Back to main</a>
            </div>
        </div>
    </div>
</div>

<script>
    function changeMainImage(imageUrl) {
        document.getElementById('mainImage').src = imageUrl;
    }
</script>

{% endblock %}

templates/sign_in.html
{% extends 'base.html' %}

{% block auth %}
<div class="columns is-centered mt-5">
    <div class="column is-3 is-9-tablet is-5-desktop is-vcentered" style="padding: 20px 0;">
        <div class="" style="box-shadow: 20px 20px 50px rgba(191, 191, 191); padding: 30px; border-radius: 10px">
            <form class="form  has-text-centered" method="post">
                <h1 class="title is-size-2 has-text-centered">Sign In</h1>
                {% csrf_token %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="button is-primary is-fullwidth">
                    Submit
                </button>
                <p class="content mt-3">
                    Don't have an account?
                    <span>
                        <a href="{% url 'sign_up' %}">Sign up here</a>
                    </span>
                </p>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/sign_up.html
{% extends 'base.html' %}

{% block auth %}
<div class="columns is-centered mt-2">
    <div class="column is-3 is-9-tablet is-5-desktop" style="padding: 20px 0;">
        <div class="" style="box-shadow: 20px 20px 50px rgba(191, 191, 191); padding: 30px; border-radius: 10px">
            <form class="form  has-text-centered" method="post">
                <h1 class="title is-size-2 has-text-centered">Sign up</h1>
                {% csrf_token %}
                {% for field in form %}
                <div class="field">
                    <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                    {{ field }}
                </div>
                {% endfor %}
                <button type="submit" class="button is-primary is-fullwidth">
                    Submit
                </button>
                <p class="content mt-3">
                    Already have an account?
                    <span>
                        <a href="{% url 'sign_in' %}">Sign in here</a>
                    </span>
                </p>
            </form>
        </div>
    </div>
</div>
{% endblock %}